export enum DocumentType {
  CI = "CI",
  CIE_FRONT = "CIE_FRONT",
  CIE_BACK = "CIE_BACK",
  DOMICILE_CERTIFICATE = "DOMICILE_CERTIFICATE",

  CIV = "CIV",
  REGISTRATION_CERTIFICATE = "REGISTRATION_CERTIFICATE",

  CONTRACT_ITL_054 = "CONTRACT_ITL_054",
  INVOICE = "INVOICE",

  FISCAL_CERTIFICATE = "FISCAL_CERTIFICATE",
  RCA = "RCA",
  CUI = "CUI",

  POWER_OF_ATTORNEY = "POWER_OF_ATTORNEY",
  DELEGATION = "DELEGATION",

  PAYMENT_PROOF = "PAYMENT_PROOF",
}